osx_image: xcode9.3
language: objective-c

before_script:
  - swift build

script:
  - set -o pipefail
  - swift test
  - swift run wsenginebuild
  - swift package generate-xcodeproj
  - swift build --configuration release --static-swift-stdlib
